### PR TITLE
Use newer Java and Gradle

### PR DESCRIPTION
**Pull request by pawbu**
Java 15 with --enable-preview is not working well in Intellij IDEA (compilation errors in places where there should not be any). 
Using Java 16 means the need to upgrade Gradle, see [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html#java).

### CODE REVIEW

**Review by DanielElisenberg — APPROVED** [review]
I'm totally ok with this! Especially as this is the only java component left in 2.0 (for now)

Make sure @vaskalan is on board too. Our 1.5 components still use an older JDK right? I think I remember having some difficulty running a newer jdk with the older gradle stuff there. I use SDKman to switch between JDKs. so this is totally fine for me at least 👍🏻 

EDIT: the build failed so something is wrong, but my sentiment remains the same

**Comment by vaskalan** [comment]
Nice! I follow you ...

**Review by DanielElisenberg — APPROVED** [review]

**Comment by pawbu** [comment]
Updating to an LTS version of Java is unproblematic. Some other dependencies needed to be updated as well.

I discovered that the Spring Boot version we used is no longer [supported](https://spring.io/projects/spring-boot#support). Fortunately there is a newer minor version that has the support.

Can you both take a new look?

**Review by DanielElisenberg — APPROVED** [review]
builds like a charm! :100:

**Pull request merged**
